/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mde;

import jade.core.AID;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author vicente
 */
public class MultimediaRequestGUI extends javax.swing.JFrame {

  /**
   * Creates new form NewJFrame
   */
  public MultimediaRequestGUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Header = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    Request = new javax.swing.JButton();
    Back = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    Header.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
    Header.setForeground(new java.awt.Color(26, 186, 56));
    Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Header.setText("Multimedia Digital Ecosystem");

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Agent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andale Mono", 1, 14))); // NOI18N

    jList1.setModel(new DefaultListModel());
    jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(jList1);

    Request.setText("Request");
    Request.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        RequestMouseClicked(evt);
      }
    });

    Back.setText("Back");
    Back.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BackMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(Back)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
        .addComponent(Request, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(214, 214, 214))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(Request, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(Back))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void RequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestMouseClicked
    // TODO add your handling code here:
    int index = jList1.getSelectedIndex();
    if(index != -1) {
      AID targetAgent = multimediaSharerGUI.getMyAgent().getRequestAgents().get(index);
      System.out.println("Target Agent: " + targetAgent.toString());
      multimediaSharerGUI.getMyAgent().addBehaviour(
                new RequestMultimediaBehaviour(targetAgent, multimediaSharerGUI.getMyAgent()));
      //Put new template hear.
    } else {
      System.out.println("Not Target Agent Selected");
    }
  }//GEN-LAST:event_RequestMouseClicked

  private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
    // TODO add your handling code here:
    multimediaSharerGUI.getMyAgent().getRequestAgents().clear();
    multimediaSharerGUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_BackMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(final MultimediaSharerGUI multimediaSharerGUI) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MultimediaRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MultimediaRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MultimediaRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MultimediaRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        MultimediaRequestGUI multimediaRequestGUI = new MultimediaRequestGUI();
        multimediaRequestGUI.setVisible(true);
        multimediaRequestGUI.setMultimediaSharerGUI(multimediaSharerGUI);
        multimediaSharerGUI.getMyAgent().addBehaviour(
                new SearchMultimediaBehaviour(multimediaRequestGUI, multimediaSharerGUI.getMyAgent()));
        multimediaRequestGUI.getHeader().setText(multimediaRequestGUI.getHeader().getText() + ":" + multimediaSharerGUI.getMyAgent().getLocalName());
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Back;
  private javax.swing.JLabel Header;
  private javax.swing.JButton Request;
  private javax.swing.JList jList1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
  private MultimediaSharerGUI multimediaSharerGUI; 

  public void drawAgents(MultimediaSharerAgent multimediaSharerAgent) {
    
    ArrayList<AID> requestAgents = multimediaSharerAgent.getRequestAgents();
    DefaultListModel model = (DefaultListModel)jList1.getModel();
    for(int i = 0; i < requestAgents.size(); ++i) {
      model.addElement(requestAgents.get(i).toString());
      //model.addElement(requestAgents.get(i).getName());
    }

  }
  
  //Getters and Setters
  
  public JButton getBack() {
    return Back;
  }

  public void setBack(JButton Back) {
    this.Back = Back;
  }

  public JLabel getHeader() {
    return Header;
  }

  public void setHeader(JLabel Header) {
    this.Header = Header;
  }

  public JButton getRequest() {
    return Request;
  }

  public void setRequest(JButton Request) {
    this.Request = Request;
  }

  public JList getjList1() {
    return jList1;
  }

  public void setjList1(JList jList1) {
    this.jList1 = jList1;
  }

  public JPanel getjPanel1() {
    return jPanel1;
  }

  public void setjPanel1(JPanel jPanel1) {
    this.jPanel1 = jPanel1;
  }

  public JScrollPane getjScrollPane1() {
    return jScrollPane1;
  }

  public void setjScrollPane1(JScrollPane jScrollPane1) {
    this.jScrollPane1 = jScrollPane1;
  }

  public MultimediaSharerGUI getMultimediaSharerGUI() {
    return multimediaSharerGUI;
  }

  public void setMultimediaSharerGUI(MultimediaSharerGUI multimediaSharerGUI) {
    this.multimediaSharerGUI = multimediaSharerGUI;
  }

}
